import Link from "next/link";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import styles from "./styles/footer.module.css";
import Navbar from "./components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
      <Navbar/>
      {children}   
      <p>It comes from layout</p>
    
       <footer className={styles.footer}>Footer This footer comes from layout</footer>
      </body>
    </html>
  );
}
